parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        dql:
            datetime_functions:
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
                now: DoctrineExtensions\Query\Mysql\Now
                day: DoctrineExtensions\Query\Mysql\Day
            string_functions:
                regexp: DoctrineExtensions\Query\Mysql\Regexp
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            App\EntityInterface\RecipeInterface: App\Recipe\Entity\Recipe
            App\EntityInterface\DirectionInterface: App\Recipe\Entity\Direction
            App\EntityInterface\IngredientInterface: App\Recipe\Entity\Ingredient
        mappings:
            App\Recipe\Entity\Recipe:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Recipe/Entity'
                prefix: 'App\Recipe\Entity'
                alias: App\Recipe\Entity
            App\Recipe\ValueObject\RecipeType:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Recipe/ValueObject'
                prefix: 'App\Recipe\ValueObject\RecipeType'
                alias: App\Recipe\ValueObject\RecipeType
            App\AMS\Entity\Administrator:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AMS/Entity'
                prefix: 'App\AMS\Entity'
                alias: App\AMS\Entity
