easy_admin:
  site_name: "What I'll Cook (WIC)"
  design:
    assets:
      css:
        # ...
        - 'bundles/easyadmin/bootstrap-all.css'
      js:
        - 'bundles/easyadmin/bootstrap-all.js'
  entities:
    Administrator:
      class: App\AMS\Entity\Administrator
    Recipe:
      class: App\Recipe\Entity\Recipe
      list:
        fields: ['id', 'uuid', 'name', 'type', 'author', 'prep', 'cook',
                 { property: 'imageUrl', type: 'url' }, 'imageSource', { property: 'approved', type: 'toggle' }, { property: 'createdAt', format: 'Y-m-d' }]
      form:
        fields: ['name',
                 { property: 'type', type: 'choice', type_options: {choices: {'BEVERAGE':'BEVERAGE', 'FOOD':'FOOD', 'INCONCLUSIVE': 'INCONCLUSIVE'}}},
                 'author', 'prep', 'cook', { property: 'imageUrl', type: 'url' }, 'imageSource']

    Ingredient:
      class: App\Recipe\Entity\Ingredient
    Direction:
      class: App\Recipe\Entity\Direction
      list:
        fields: ['id', 'description', 'recipe']
    Unknown:
      class: App\Recipe\Entity\Unknown