nelmio_api_doc:
    documentation:
        info:
            title: wic REST API
            description: WIC is a acronym for What I'll cook and this API serves the purpose of providing food recipes. Get loads of inspiration of what to cook just with an ingredient or a meal content of the dish.
            version: v1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc